name=SparkFun SSD168x I2C Interface Library
version=1.0.0
author=SparkFun Electronics <techsupport@sparkfun.com>
maintainer=SparkFun Electronics <sparkfun.com>
sentence=Library for SSD168x e-paper displays on I2C
paragraph=A library to support SSD168x e-paper displays on I2C using a I2C-SPI Bridge. The MSP430FR2433 and STM32G03 folders contain example bridge firmware
category=Display
url=https://github.com/sparkfun/SparkFun_SSD168x_I2C_Interface_Library
architectures=*